### ISSUE TITLE
Match Making Not Working

### ISSUE THREAD

**Issue by LeaguezOG** [karimkanafani/NFTLeaguez#14]
User 1 - Alienware Laptop, Google Chrome, Phantom Wallet, 4 NFT's

User 2 - MacBook Laptop, Google Chrome, Phantom Wallet, 40 NFT's.

Both users NFT's loaded.

Match Making Not Working.

Had user on screenshare while connecting.

<img width="1728" alt="Screenshot 2023-09-02 at 5 32 39 pm" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/7a402707-0b9c-4c40-b5ba-960629be280f">

**Comment by karimkanafani** [comment]
In the matchmaking optimization I made, it prioritized region for ping. But I guess that broke something. I reverted it to the old matchmaking while I investigate. Tested it again, it works now.
