### ISSUE TITLE
So a couple things I'm getting.  Sometimes I get the ArgumentNullException errors as shown in the pic.  Then the last couple times I just get the ball and nothing else.  Does someone else have to be on or is this just me vs. the computer?

### ISSUE THREAD

**Issue by lawhun** [karimkanafani/NFTLeaguez#2]
So a couple things I'm getting.  Sometimes I get the ArgumentNullException errors as shown in the pic.  Then the last couple times I just get the ball and nothing else.  Does someone else have to be on or is this just me vs. the computer?

1. After connecting wallet the ArgumentNullException errors shows.
2. Then went to roster and it showed again.
3. Going back to play it showed again.
4. It allows me to go into a game and then after selecting the team I just get the ball bouncing around.
5. Not sure if this is searching for another player or if it should play against the system / simulator.

![image](https://github.com/karimkanafani/NFTLeaguez/assets/7252549/6679f9f2-1936-41df-a212-e384f71db8c6)

**Comment by karimkanafani** [comment]
These issues should be solved in the newest patch released!
