### ISSUE TITLE
Dev Tools Not Loading

### ISSUE THREAD

**Issue by LeaguezOG** [karimkanafani/NFTLeaguez#4]
**Describe the bug**

These issues should be looked at.

<img width="586" alt="Screenshot 2023-08-26 at 12 02 58 am" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/9410bbd2-7925-4969-b465-fe1001709841">

**Comment by karimkanafani** [comment]
These are normal as we don't use them in this game. It should not have any impact on the game!
