### ISSUE TITLE
Multiple Error messages

### ISSUE THREAD

**Issue by LeaguezOG** [karimkanafani/NFTLeaguez#5]
These are appearing at the bottom of the screen.

<img width="606" alt="Screenshot 2023-08-26 at 12 02 44 am" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/cf0fee76-10b5-4e6b-8e23-677a3e63707a">
<img width="593" alt="Screenshot 2023-08-26 at 12 05 17 am" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/86d82e03-1a70-4c87-8a26-2cf75191bfd4">
<img width="401" alt="Screenshot 2023-08-26 at 12 12 44 am" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/0c410489-49f7-429f-b6a5-53f3372d9111">

**Comment by karimkanafani** [comment]
All these issues should be resolved in the newest patch
