### ISSUE TITLE
Leaderboard Bug - Position not showing

### ISSUE THREAD

**Issue by LeaguezOG** [karimkanafani/NFTLeaguez#6]
My version is: Chrome 116 on macOS (Ventura)

When I connect wallet, my position doesn't load on leader board.

<img width="1202" alt="Screenshot 2023-08-26 at 12 29 09 am" src="https://github.com/karimkanafani/NFTLeaguez/assets/143053875/22897b5e-8806-4cf2-83fd-08ae610d49e6">

**Comment by karimkanafani** [comment]
Where you connected before clicking on the Leaderboard tab? or did you connect wallet while on this page?
If wallet was connected while on this page, then this is normal, you just need to go to another page (Roster, Play, Main for example) then go back to the leaderboard page to see your position.
